config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "/home", to: "home#index", as: "home"
 
  get '/turns/:id/attend', to: 'turns#attend', as: 'attend_turn'

  resources :users
  resources :turns
  resources :bank_branches do
      resources :schedules
  end    
  resources :localities
  resources :sessions, only: [:new, :create, :destroy] 
end

app/models/bank_branch.rb
class BankBranch < ApplicationRecord
    validates :name, :address, :phone, presence: { message: "No puede ser nulo"}
    validates :name, uniqueness: { message: "Ya existe esta Sucursal" }
    belongs_to :locality
    has_many :schedules, dependent: :destroy
    has_many :turns, dependent: :destroy
        
    def to_string
        "#{name.capitalize} - #{locality.to_string}"
    end

    def has_pending_turns?
        turns.where(state: :Pendiente).present? 
    end   
    
end

app/controllers/bank_branches_controller.rb
class BankBranchesController < ApplicationController
  before_action :set_bank_branch, only: %i[ show edit update destroy ]

  # GET /bank_branches or /bank_branches.json
  def index
    @bank_branches = BankBranch.order(:name)
  end

  # GET /bank_branches/1 or /bank_branches/1.json
  def show
    @schedules = @bank_branch.schedules.order(:weekday)
  end

  # GET /bank_branches/new
  def new
    @bank_branch = BankBranch.new
  end

  # GET /bank_branches/1/edit
  def edit
  
  end

  # POST /bank_branches or /bank_branches.json
  def create
    @bank_branch = BankBranch.new(bank_branch_params)
    
    respond_to do |format|
      if @bank_branch.save
        format.html { redirect_to bank_branch_url(@bank_branch), notice: "Sucursal Bancaria agregada exitosamente ✅" }
        format.json { render :show, status: :created, location: @bank_branch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bank_branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_branches/1 or /bank_branches/1.json
  def update
    respond_to do |format|
      if @bank_branch.update(bank_branch_params)
        format.html { redirect_to bank_branch_url(@bank_branch), notice: "Sucursal Bancaria modificada exitosamente ✅" }
        format.json { render :show, status: :ok, location: @bank_branch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bank_branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_branches/1 or /bank_branches/1.json
  def destroy
    @bank_branch.destroy

    respond_to do |format|
      format.html { redirect_to bank_branches_url, notice: "Sucursal Bancaria eliminada exitosamente ✅" }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_branch
      @bank_branch = BankBranch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bank_branch_params
      params.require(:bank_branch).permit(:name, :address, :phone, :locality_id)
    end
end

app/helpers/bank_branches_helper.rb
module BankBranchesHelper

    def bank_branches_available
       BankBranch.joins(:schedules).where("schedules.id IS NOT NULL").distinct.order(name: :asc)
    end   
    
    def ordered_localities 
        Locality.order(province: :asc , name: :asc)
    end    

end

app/views/bank_branches/_bank_branch.html.erb
<div class="container">
   <tr>
    <td> <%= bank_branch.id %></td>
    <td> <%= bank_branch.name %></td>
    <td> <%= bank_branch.address %></td>
    <td> <%= bank_branch.locality.name %></td>
    <td> <%= bank_branch.locality.province %></td>
       <% if current_user.Administrador? %>  
         <td> <%= link_to 'Editar', edit_bank_branch_path(bank_branch), :class => "btn btn-primary btn-sm" %> </td>
         <td> <%= button_to "Eliminar", bank_branch_path(bank_branch), 
             {:onclick => "return confirm('Confirma el borrado?')", :class => "btn btn-danger btn-sm",
              :method => :delete, :disabled => (bank_branch.has_pending_turns?) }%> </td>
         <td> <%= link_to bank_branch_schedules_path(bank_branch, @schedules), class: "btn btn-icon" do %>
                 <i class="fa fa-calendar" aria-hidden="true"></i>
              <% end %> </td>  
       <% end %>               
    <td> <%= link_to bank_branch_path(bank_branch), class: "btn btn-icon" do %>
           <i class="fa fa-eye" aria-hidden="true"></i>
         <% end %> </td>
          
    <br>
   </tr> 
</div>

app/views/bank_branches/_form.html.erb
<%= form_with(model: @bank_branch) do |form| %>
   <% if @bank_branch.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>🚫Atención hay errores:</strong>
      <ul>
        <% @bank_branch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container">
    <div class="form-group">  
             
       <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name, class:'form-control' %>
       </div>

        <div>
        <%= form.label :address, style: "display: block" %>
        <%= form.text_field :address, class:'form-control' %>
       </div>

       <div>
        <%= form.label :locality, style: "display: block"%>
        <%= form.collection_select :locality_id, ordered_localities, 
              :id, :to_string %>
       </div>

       <div>
        <%= form.label :phone, style: "display: block" %>
        <%= form.text_field :phone, class:'form-control' %>
       </div> 
       
       <div>
         <br> 
         <%= form.submit "Guardar Sucursal Bancaria", :class => "btn btn-outline-success"  %>
       </div>
    </div>
  </div>     
<% end %>

app/views/bank_branches/edit.html.erb
<div class="container">
    <h1><strong> Modificar Sucursal Bancaria </strong></h1>
    <%= render 'form' %><br>
    <%= link_to "Volver a las Sucursales Bancarias", bank_branches_path %>
</div>

app/views/bank_branches/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1><strong> Lista de Sucursales Bancarias</strong></h1>
  <div class="row">
    <table class="table table-bordered">
      <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Localidad</th>
                <th>Provincia</th>
            </tr>
      </thead> 
      <tbody>
        <%= render @bank_branches %>
      </tbody> 
    </table>   
  </div>
   <% if current_user.Administrador? %> 
    <%= link_to 'Agregar Sucursal Bancaria', new_bank_branch_path, :class => "btn btn-success btn-lg" %>
   <% end %> 
  <br>
  <br>
  <%= link_to "Volver a la pantalla principal", home_path %>

app/views/bank_branches/new.html.erb
<div class="container">
  <h1><strong> Nueva Sucursal Bancaria </strong></h1>

  <%= render "form", bank_branch: @bank_branch %>

  <br>

  <div>
    <%= link_to "Volver a las Sucursales Bancarias", bank_branches_path %>
  </div>
</div>

app/views/bank_branches/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <br>
  <h4><strong> Sucursal Bancaria Nombre: <%= @bank_branch.name.capitalize %></strong></h4>
  <strong> Dirección: </strong> <%= @bank_branch.address %><br>
  <strong> Localidad: </strong> <%= @bank_branch.locality.name %>
  <strong> Provincia: </strong> <%= @bank_branch.locality.province %><br>
  <strong> Teléfono: </strong> <%= @bank_branch.phone %>
  <br>
  <h5><strong> Horarios de Atención </strong></h5>
  <div class="row">
    <table class="table table-bordered">
      <thead>
            <tr>
                <th>Día de la semana</th>
                <th>Horario desde</th>
                <th>Horario hasta</th>
            </tr>
      </thead> 
      <tbody>
         <% @schedules.each do |row| %>
            <tr>
               <td><%= row.weekday %></td>
               <td><%= row.start_time.strftime("%H:%M") %></td>
               <td><%= row.end_time.strftime("%H:%M") %></td>
            </tr>
         <% end %>   
      </tbody> 
    </table>   
  </div> 
  
  <br>
  <%= link_to "Volver a las Sucursales Bancarias", bank_branches_path %>
</div>