config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "/home", to: "home#index", as: "home"
 
  get '/turns/:id/attend', to: 'turns#attend', as: 'attend_turn'

  resources :users
  resources :turns
  resources :bank_branches do
      resources :schedules
  end    
  resources :localities
  resources :sessions, only: [:new, :create, :destroy] 
end

app/models/locality.rb
class Locality < ApplicationRecord
    validates :name, :province, presence: { message: "No puede ser nulo"}
    validates :name, uniqueness: { scope: :province, 
        message: "Ya existe esta Localidad" }
    has_many :bank_branches
    validate :no_branches_associated, on: :destroy
      
    def to_string
        "#{province} - #{name}"
    end

    def no_branches_associated
        if bank_branches.any?
            errors.add(:base, "Existen Sucursales Bancarias asociadas a esta Localidad")
            throw :abort
        end
    end

end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :set_locality, only: %i[ show edit update destroy ]

  # GET /localities or /localities.json
  def index
    @localities = Locality.all
  end

  # GET /localities/1 or /localities/1.json
  def show
  end

  # GET /localities/new
  def new
    @locality = Locality.new
  end

  # GET /localities/1/edit
  def edit
  end

  # POST /localities or /localities.json
  def create
    @locality = Locality.new(locality_params)

    respond_to do |format|
      if @locality.save
        format.html { redirect_to locality_url(@locality), notice: "Localidad agregada exitosamente ✅" }
        format.json { render :show, status: :created, location: @locality }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /localities/1 or /localities/1.json
  def update
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to locality_url(@locality), notice: "Localidad actualizada exitosamente ✅" }
        format.json { render :show, status: :ok, location: @locality }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localities/1 or /localities/1.json
  def destroy
    @locality.destroy

    respond_to do |format|
      format.html { redirect_to localities_url, notice: "Localidad eliminada exitosamente ✅" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locality
      @locality = Locality.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def locality_params
      params.require(:locality).permit(:name, :province)
    end
end

app/helpers/localities_helper.rb
module LocalitiesHelper

    def argentine_provinces
        ["Buenos Aires", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", 
            "Entre Rios", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", 
            "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe",
             "Santiago del Estero", "Tierra del Fuego", "Tucumán"
             ]
    end

end    

app/views/localities/_form.html.erb
<%= form_with model: @locality do |form| %>
  <% if @locality.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>🚫Atención hay errores:</strong>
      <ul>
        <% @locality.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="form-group">  
     <div>      
      <%= form.label :name %><br>
      <%= form.text_field :name, class:'form-control'  %>
      <%= form.label :province %><br>
      <%= form.select :province, options_for_select(argentine_provinces, :selected => form.object.province) %><br>
      </div>   
      <div>
       <%= form.submit "Guardar Localidad", :class => "btn btn-outline-success mt-2"  %>
      </div>   
  </div>    

<% end %>

app/views/localities/_locality.html.erb
<div class="container">
   <tr>
    <td> <%= locality.id %></td>
    <td> <%= locality.name %></td>
    <td> <%= locality.province %></td>
    <td> <%= link_to 'Editar', edit_locality_path(locality), :class => "btn btn-primary btn-sm" %> </td>
    <td> <%= button_to "Eliminar", locality_path(locality), 
             {:onclick => "return confirm('Confirma el borrado?')", :class => "btn btn-danger btn-sm",
              :method => :delete, :disabled => (locality.bank_branches.any?) }%> </td>
    <br>
   </tr> 
</div>

app/views/localities/edit.html.erb
<div class="container">
    <h1><strong> Editar Localidad </strong></h1>
    <%= render 'form' %><br>
    <%= link_to "Volver a las Localidades", localities_path %>
</div>

app/views/localities/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1><strong> Lista de Localidades</strong></h1>
  <div class="row">
    <table class="table table-bordered">
      <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Provincia</th>
            </tr>
      </thead> 
      <tbody>
        <%= render @localities %>
      </tbody> 
    </table>   
  </div>
  <%= link_to 'Agregar Localidad', new_locality_path, :class => "btn btn-success btn-lg" %>
  <br>
  <br>
  <%= link_to "Volver a la pantalla principal", home_path %>

app/views/localities/new.html.erb
 
 <div class="container">
  <h1><strong> Nueva Localidad </strong></h1>

  <%= render "form", locality: @locality %>

  <br>

  <div>
    <%= link_to "Volver a las Localidades", localities_path %>
  </div>

app/views/localities/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <strong> Nombre: </strong> <%= @locality.name %><br>
  <strong> Provincia: </strong> <%= @locality.province %>
  <br>
  <%= link_to "Volver a las Localidades", localities_path %>
</div>