config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "/home", to: "home#index", as: "home"
 
  get '/turns/:id/attend', to: 'turns#attend', as: 'attend_turn'

  resources :users
  resources :turns
  resources :bank_branches do
      resources :schedules
  end    
  resources :localities
  resources :sessions, only: [:new, :create, :destroy] 
end

app/models/turn.rb
class Turn < ApplicationRecord
    validates :date, :time, :reason, :state, presence: { message: "No puede ser nulo"}
    validate  :date_and_time, if: -> { date.present? && time.present? }
    validates :comment, presence: true, if: -> { employee.present? }
    attribute :state, :integer, default: 0        
    belongs_to :bank_branch
    belongs_to :user
    belongs_to :employee, class_name: "User", optional:true
    
    enum state: [:Pendiente, :Atendido, :NoAtendido]   
   
    
    def date_and_time
         if date_valid?    
            schedule = bank_branch.schedules.where(weekday: date.wday).first
            weekdays = bank_branch.schedules.order(:weekday).pluck(:weekday)
            if schedule.nil?
                errors.add(:date, "La Sucursal Bancaria solo atiende los días #{weekdays.join(', ')}")
            elsif schedule.start_time > time || schedule.end_time < time
                errors.add(:time, "La Sucursal Bancaria atiende entre las
                    #{schedule.start_time.strftime("%H:%M")}
                    y las #{schedule.end_time.strftime("%H:%M")} hs.") 
            end 
        else
            errors.add(:date, "La fecha seleccionada es anterior al día de hoy")
        end 
    end

    def date_valid?
        date >= Date.today 
    end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :set_turn, only: %i[ show edit attend update destroy ]

  # GET /turns or /turns.json
  def index
    if Current&.user.Personal?
        @turns = Turn.where(bank_branch_id: Current.user.bank_branch_id).order(:date)
    elsif
      if Current&.user.Cliente?
        @turns = Turn.where(user_id: Current.user.id).order(:date)
      end 
    else 
        @turns = Turn.order(:date)
    end   
  end

  # GET /turns/1 or /turns/1.json
  def show
  end

  # GET /turns/new
  def new
    @turn = Turn.new
  end

  # GET /turns/1/edit
  def edit
  end

  # GET /turns/1/attend
  def attend
  end


  # POST /turns or /turns.json
  def create
    @turn = Turn.new(turn_params)
    @turn.user_id = Current.user.id

    respond_to do |format|
      if @turn.save
        format.html { redirect_to turn_url(@turn), notice: "El turno se creó correctamente ✅" }
        format.json { render :show, status: :created, location: @turn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turns/1 or /turns/1.json
  def update
      if Current.user.Personal?
         @turn.employee_id = Current.user.id
         @turn.state = :Atendido
      end  
      if @turn.update(turn_params)
          if Current.user.Personal?
             redirect_to turn_url(@turn), notice: "Turno atendido correctamente ✅"    
          else
             redirect_to turn_url(@turn), notice: "Turno actualizado correctamente ✅"
          end
      else
          if Current.user.Personal?
            render :attend, status: :unprocessable_entity
          else
            render :edit, status: :unprocessable_entity
          end  
      end
  end
  
  # DELETE /turns/1 or /turns/1.json
  def destroy
    @turn.destroy

    respond_to do |format|
      format.html { redirect_to turns_url, notice: "Turn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn
      @turn = Turn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turn_params
      params.require(:turn).permit(:date, :time, :reason, :state, :comment, :bank_branch_id, 
                             :employee_id, :user_id)
    end
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/turns/_form.html.erb
<%= form_with(model: @turn) do |form| %>
   <% if @turn.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>🚫Atención hay errores:</strong>
      <ul>
        <% @turn.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container">
    <div class="form-group">  
       
       <div>
        <%= form.label "Sucursal Bancaria", style: "display: block"%>
        <%= form.collection_select :bank_branch_id, bank_branches_available, 
              :id, :to_string %>
       </div>

       <div>
          <%= form.label :date, style: "display: block" %>
          <%= form.date_field :date %>
       </div>

       <div>
          <%= form.label :time, style: "display: block" %>
          <%= form.time_field :time %>
       </div>

       <div>
          <%= form.label :reason, style: "display: block" %>
          <%= form.text_field :reason %>
       </div> 

       <div>
         <br> 
         <%= form.submit "Solicitar Turno", :class => "btn btn-outline-success"  %>
       </div>
    </div>
  </div>     
<% end %>

app/views/turns/_form_attend.html.erb
<%= form_with(model: @turn) do |form| %>
   <% if @turn.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>🚫Atención hay errores:</strong>
      <ul>
        <% @turn.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container">
    <div class="form-group">  
       
       <div>
            <h5><strong> Sucursal Nombre: <%= @turn.bank_branch.to_string %> </strong></h5>
            <strong> Cliente: </strong> <%= @turn.user.username %><br> 
            <strong> Fecha: </strong> <%= I18n.l(@turn.date, format: "%A, %d-%m-%y") %><br>
            <strong> Horario: </strong> <%= @turn.time.strftime("%H:%M") %><br>
            <strong> Motivo: </strong> <%= @turn.reason %>
       </div>
             
       <div>
          <strong> <%= form.label :comment, style: "display: block" %> </strong>
          <%= form.text_field :comment %>
       </div> 

       <div>
         <br> 
         <%= form.submit "Registrar Atención", :class => "btn btn-outline-success"  %>
       </div>
    </div>
  </div>     
<% end %>

app/views/turns/_turn.html.erb
<div class="container">
   <tr>
    <td> <%= turn.bank_branch.to_string %></td>
    <td> <%= turn.user.username %></td>
    <td> <%= I18n.l(turn.date, format: "%A, %d-%m-%y") %></td>
    <td> <%= turn.time.strftime("%H:%M")%></td>
    <td> <%= turn.reason %></td>
    <td style="color: <%= turn.Pendiente? ? 'blue' : 'green' %>">
        <%= turn.state %></td>
     
    <% if turn.Pendiente? && current_user.Cliente? %>
        <td> <%= link_to 'Modificar', edit_turn_path(turn), :class => "btn btn-primary btn-sm" %> </td>
        <td> <%= button_to "Cancelar", turn_path(turn), 
                  {:onclick => "return confirm('Confirma la cancelación?')", :class => "btn btn-danger btn-sm",
                  :method => :delete, :disabled => (turn.date > Date.today ? false : true) }%> </td>
    <% end %>
    <% if turn.Pendiente? && current_user.Personal? && turn.date <= Date.today %>
        <td> <%= link_to 'Atender', attend_turn_path(turn), :class => "btn btn-success btn-sm" %> </td>
    <% end %>
    <% if !turn.Pendiente? %>
      <td> <%= link_to turn_path(turn), class: "btn btn-icon" do %>
            <i class="fa fa-eye" aria-hidden="true"></i>
            <% end %> </td>
    <% end %>                 
    <br>
   </tr> 
</div>

app/views/turns/attend.html.erb
<div class="container">
  <h3><strong> Atendiendo Turno Personal Bancario: <%= current_user.username %> </strong></h3>
  <%= render "form_attend", turn: @turn %>
  <br>
  <div>
    <%= link_to "Volver a mis turnos", turns_path %>
  </div>
</div>

app/views/turns/edit.html.erb
<div class="container">
  <h2><strong> Modificar Turno de Atención</strong></h2>
  <%= render "form", turn: @turn %>
  <br>
  <div>
    <%= link_to "Volver a mis turnos", turns_path %>
  </div>
</div>

app/views/turns/index.html.erb
<div class="container">
  <h2><strong> Turnos de Atención</strong></h2>
  <div class="row">
    <table class="table table-bordered">
      <thead>
            <tr>
                <th>Sucursal</th>
                <th>Cliente</th>
                <th>Fecha</th>
                <th>Horario</th>
                <th>Motivo</th>
                <th>Estado</th>
            </tr>
      </thead> 
      <tbody>
        <%= render @turns %>
      </tbody> 
    </table>   
  </div>
   <% if current_user.Cliente? %> 
    <%= link_to 'Nuevo Turno', new_turn_path, :class => "btn btn-success btn-lg" %>
   <% end %>
</div>
 <br>
  <br>
  <%= link_to "Volver a la pantalla principal", home_path %>   

app/views/turns/new.html.erb
 <div class="container">
  <h2><strong> Solicitud de Turno de Atención </strong></h2>
  <%= render "form", turn: @turn %>
  <br>
  <div>
    <%= link_to "Volver a mis turnos", turns_path %>
  </div>
 </div>

app/views/turns/show.html.erb
<div class="container">
  <h2><strong> Turno en Sucursal Nombre: <%= @turn.bank_branch.to_string %> </strong></h2> 
  <p style="color: green"><%= notice %></p>
  <strong> Fecha: </strong> <%= I18n.l(@turn.date, format: "%A, %d-%m-%y") %><br>
  <strong> Horario: </strong> <%= @turn.time.strftime("%H:%M") %><br>
  <strong> Motivo: </strong> <%= @turn.reason %><br>
  <% if @turn.Atendido? %>  
    <strong> Atendido por: </strong> <%= @turn.employee.username %><br>
    <strong> Motivo: </strong> <%= @turn.comment %><br>
  <% end %>
  <br>
  <br>
  <%= link_to "Volver a mis turnos", turns_path %>
</div>